module.exports = {
  semi: false,
  singleQuote: false,
  quoteProps: "as-needed",
  tabWidth: 2,
  useTabs: false,
  trailingComma: "none",
  printWidth: 120,
  bracketSpacing: true,
  bracketSameLine: false,
  arrowParens: "always",
  endOfLine: "lf",
  embeddedLanguageFormatting: "auto",
  htmlWhitespaceSensitivity: "css",
  insertPragma: false,
  jsxSingleQuote: false,
  proseWrap: "preserve",
  requirePragma: false,
  vueIndentScriptAndStyle: false,
  singleAttributePerLine: false,
  importOrder: [
    "^(react/(.*)$)|^(react$)",
    "^(react-native/(.*)$)|^(react-native$)",
    "^(expo/(.*)$)|^(expo$)",
    "<BUILTIN_MODULES>",
    "<THIRD_PARTY_MODULES>",
    "^@/components/charts/(.*)$",
    "^@/components/common/(.*)$",
    "^@/components/features/(.*)$",
    "^@/components/forms/(.*)$",
    "^@/components/layout/(.*)$",
    "^@/components/nativewindui/(.*)$",
    "^@/components/ui/(.*)$",
    "^@/config/(.*)$",
    "^@/constants/(.*)$",
    "^@/contexts/(.*)$",
    "^@/hooks/(.*)$",
    "^@/lib/(.*)$",
    "^@/providers/(.*)$",
    "^@/services/(.*)$",
    "^@/stores/(.*)$",
    "^@/styles/(.*)$",
    "^@/types/(.*)$",
    "^@/utils/(.*)$",
    "^@/validations/(.*)$",
    "^@/(.*)$",
    "^[./]"
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  plugins: ["@trivago/prettier-plugin-sort-imports", "prettier-plugin-packagejson", "prettier-plugin-tailwindcss"],
  tailwindAttributes: ["className"]
}
